[package]
name = "scbdb-scraper"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
reqwest.workspace = true
scbdb-core = { path = "../scbdb-core" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
