[package]
name = "scbdb-sentiment"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
scbdb-core = { path = "../scbdb-core" }
serde.workspace = true
