[package]
name = "scbdb-db"
version = "0.1.0"
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
scbdb-core = { path = "../scbdb-core" }
sqlx.workspace = true
tracing.workspace = true
